In [1]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ──────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [7]:
nhl_players <- readRDS ("Predict NHL Breakout 26-27/nhl_players.rds")

In [42]:
nhl_players <- nhl_players |>
    filter(situation == "all")

nrow(nhl_players)

[1] 10115

In [9]:
nhl_players <- nhl_players |>
    select (where(~ !all(is.na(.))))

In [44]:
invisible(colnames(nhl_players))

In [46]:
nhl_clean <- nhl_players |>
    transmute(
        player_id = playerId,
        player_name = name,
        season_start = season,
        team,
        position,
        games_played, 

        total_minutes = icetime/ 60,
        average_minutes = total_minutes / games_played, 

        goals = I_F_goals, 
        primary_assists = I_F_primaryAssists, 
        secondary_assists = I_F_secondaryAssists,
        assists = primary_assists + secondary_assists,
        points = I_F_points,
    
        points_per_game = points / games_played,
        points_per_82 = points_per_game * 82
  )

In [47]:
nrow(nhl_clean)

[1] 10115

In [17]:
ncol(nhl_clean)

[1] 15

In [48]:
print(
    head(nhl_clean, 20),
    n = 20
    )

# A tibble: 20 × 15
   player_id player_name  season_start team  position games_played total_minutes
       <dbl> <chr>               <dbl> <chr> <chr>           <dbl>         <dbl>
 1   8469459 Mikko Koivu          2015 MIN   C                  82        1634.
 2   8477845 Trevor van …         2015 CHI   D                  82        1639.
 3   8470724 Kyle Quincey         2015 DET   D                  47         929.
 4   8476887 Filip Forsb…         2015 NSH   L                  82        1562.
 5   8466285 Brian Campb…         2015 FLA   D                  82        1827.
 6   8474052 Chris Terry          2015 CAR   L                  68         767.
 7   8478393 Kyle Baun            2015 CHI   R                   2          18.1
 8   8474037 James van R…         2015 TOR   L                  40         711.
 9   8476449 Scott Harri…         2015 TOR   D                  15         196.
10   8475727 Ryan Spooner         2015 BOS   C                  80        1211.
11   8475728 Johan Larss…         2015 BUF   C                  74        1097.
12   8477504 Josh Morris…         2015 WPG   D                   1          15.9
13   8477006 Christoph B…         2015 MIN   C                   3          20.8
14   8476370 Blake Pieti…         2015 N.J   L                   7          84.2
15   8473546 Michael Gra…         2015 TOR   R                  80        1158.
16   8477510 Kerby Rychel         2015 CBJ   L                  32         304.
17   8475178 Zack Kassian         2015 EDM   R                  36         448.
18   8477958 Nikolay Gol…         2015 S.J   R                   9         101.
19   8473468 Eric Gryba           2015 EDM   D                  53         948.
20   8468575 Dominic Moo…         2015 NYR   C                  80        1064.
# ℹ 8 more variables: average_minutes <dbl>, goals <dbl>,
#   primary_assists <dbl>, secondary_assists <dbl>, assists <dbl>,
#   points <dbl>, points_per_game <dbl>, points_per_82 <dbl>

In [49]:
player_bios <- read_csv(
    "Predict NHL breakout 26-27/player_bios.csv",
    show_col_types = FALSE
    )
names(player_bios)
head(player_bios)

 [1] "playerId"        "name"            "position"        "team"
 [5] "birthDate"       "weight"          "height"          "nationality"
 [9] "shootsCatches"   "primaryNumber"   "primaryPosition"

  playerId name          position team birthDate  weight height nationality
1 8478421  A.J. Greer    L        FLA  1996-12-14 210    6' 3"  CAN
2 8477180  Aaron Dell    G        SJS  1989-05-04 205    6' 0"  CAN
3 8465992  Aaron Downey  R        DET  1974-08-27 215    6' 1"  CAN
4 8477932  Aaron Ekblad  D        FLA  1996-02-07 220    6' 4"  CAN
5 8471451  Aaron Gagnon  C        WPG  1986-04-24 186    5' 11" CAN
6 8469534  Aaron Johnson D        BOS  1983-04-30 204    6' 1"  CAN
  shootsCatches primaryNumber primaryPosition
1 L             24            L
2 L             30            G
3 R             44            R
4 R              5            D
5 R             21            C
6 L             72            D

In [50]:
player_bios_clean <- player_bios |>
    transmute(
        player_id = playerId,
        birth_date = as.Date(birthDate)
        )

In [51]:
nhl_clean <- nhl_clean |>
    left_join(
        player_bios_clean,
        by = "player_id"
        )

In [53]:
head(nhl_clean, 20)

   player_id player_name         season_start team position games_played
1  8469459   Mikko Koivu         2015         MIN  C        82
2  8477845   Trevor van Riemsdyk 2015         CHI  D        82
3  8470724   Kyle Quincey        2015         DET  D        47
4  8476887   Filip Forsberg      2015         NSH  L        82
5  8466285   Brian Campbell      2015         FLA  D        82
6  8474052   Chris Terry         2015         CAR  L        68
7  8478393   Kyle Baun           2015         CHI  R         2
8  8474037   James van Riemsdyk  2015         TOR  L        40
9  8476449   Scott Harrington    2015         TOR  D        15
10 8475727   Ryan Spooner        2015         BOS  C        80
11 8475728   Johan Larsson       2015         BUF  C        74
12 8477504   Josh Morrissey      2015         WPG  D         1
13 8477006   Christoph Bertschy  2015         MIN  C         3
14 8476370   Blake Pietila       2015         N.J  L         7
15 8473546   Michael Grabner     2015         TOR  R        80
16 8477510   Kerby Rychel        2015         CBJ  L        32
17 8475178   Zack Kassian        2015         EDM  R        36
18 8477958   Nikolay Goldobin    2015         S.J  R         9
19 8473468   Eric Gryba          2015         EDM  D        53
20 8468575   Dominic Moore       2015         NYR  C        80
   total_minutes average_minutes goals primary_assists secondary_assists
1  1634.18333    19.929065       17    18              21
2  1638.66667    19.983740        3     7               4
3   928.88333    19.763475        4     0               7
4  1562.31667    19.052642       33    14              17
5  1826.78333    22.277846        6    12              13
6   766.68333    11.274755        8     2               1
7    18.10000     9.050000        0     0               0
8   710.51667    17.762917       14    10               5
9   196.41667    13.094444        0     0               1
10 1211.28333    15.141042       13    29               7
11 1096.65000    14.819595       10     5               2
12   15.90000    15.900000        0     0               0
13   20.83333     6.944444        0     0               0
14   84.23333    12.033333        1     1               0
15 1157.53333    14.469167        9     5               4
16  304.45000     9.514062        2     6               1
17  448.26667    12.451852        3     2               3
18  100.66667    11.185185        1     1               0
19  947.76667    17.882390        1     2               3
20 1063.60000    13.295000        6     5               4
   assists points points_per_game points_per_82 birth_date
1  39      56     0.68292683      56.000000     1983-03-12
2  11      14     0.17073171      14.000000     1991-07-24
3   7      11     0.23404255      19.191489     1985-08-12
4  31      64     0.78048780      64.000000     1994-08-13
5  25      31     0.37804878      31.000000     1979-05-23
6   3      11     0.16176471      13.264706     1989-04-07
7   0       0     0.00000000       0.000000     <NA>
8  15      29     0.72500000      59.450000     1989-05-04
9   1       1     0.06666667       5.466667     1993-03-10
10 36      49     0.61250000      50.225000     1992-01-30
11  7      17     0.22972973      18.837838     1992-07-25
12  0       0     0.00000000       0.000000     1995-03-28
13  0       0     0.00000000       0.000000     1994-04-05
14  1       2     0.28571429      23.428571     1993-02-20
15  9      18     0.22500000      18.450000     1987-10-05
16  7       9     0.28125000      23.062500     1994-10-07
17  5       8     0.22222222      18.222222     1991-01-24
18  1       2     0.22222222      18.222222     1995-10-07
19  5       6     0.11320755       9.283019     1988-04-14
20  9      15     0.18750000      15.375000     1980-08-03

In [55]:
nhl_clean <- nhl_clean |>
    mutate(
        season_date = as.Date (
            paste0(season_start, "-10-01")
            ),

        age = as.numeric (
            difftime(
                season_date,
                birth_date,
                units = "days"
                )
            ) / 365.25
        )
head(nhl_clean, 20)

   player_id player_name         season_start team position games_played
1  8469459   Mikko Koivu         2015         MIN  C        82
2  8477845   Trevor van Riemsdyk 2015         CHI  D        82
3  8470724   Kyle Quincey        2015         DET  D        47
4  8476887   Filip Forsberg      2015         NSH  L        82
5  8466285   Brian Campbell      2015         FLA  D        82
6  8474052   Chris Terry         2015         CAR  L        68
7  8478393   Kyle Baun           2015         CHI  R         2
8  8474037   James van Riemsdyk  2015         TOR  L        40
9  8476449   Scott Harrington    2015         TOR  D        15
10 8475727   Ryan Spooner        2015         BOS  C        80
11 8475728   Johan Larsson       2015         BUF  C        74
12 8477504   Josh Morrissey      2015         WPG  D         1
13 8477006   Christoph Bertschy  2015         MIN  C         3
14 8476370   Blake Pietila       2015         N.J  L         7
15 8473546   Michael Grabner     2015         TOR  R        80
16 8477510   Kerby Rychel        2015         CBJ  L        32
17 8475178   Zack Kassian        2015         EDM  R        36
18 8477958   Nikolay Goldobin    2015         S.J  R         9
19 8473468   Eric Gryba          2015         EDM  D        53
20 8468575   Dominic Moore       2015         NYR  C        80
   total_minutes average_minutes goals primary_assists secondary_assists
1  1634.18333    19.929065       17    18              21
2  1638.66667    19.983740        3     7               4
3   928.88333    19.763475        4     0               7
4  1562.31667    19.052642       33    14              17
5  1826.78333    22.277846        6    12              13
6   766.68333    11.274755        8     2               1
7    18.10000     9.050000        0     0               0
8   710.51667    17.762917       14    10               5
9   196.41667    13.094444        0     0               1
10 1211.28333    15.141042       13    29               7
11 1096.65000    14.819595       10     5               2
12   15.90000    15.900000        0     0               0
13   20.83333     6.944444        0     0               0
14   84.23333    12.033333        1     1               0
15 1157.53333    14.469167        9     5               4
16  304.45000     9.514062        2     6               1
17  448.26667    12.451852        3     2               3
18  100.66667    11.185185        1     1               0
19  947.76667    17.882390        1     2               3
20 1063.60000    13.295000        6     5               4
   assists points points_per_game points_per_82 birth_date season_date age
1  39      56     0.68292683      56.000000     1983-03-12 2015-10-01  32.55578
2  11      14     0.17073171      14.000000     1991-07-24 2015-10-01  24.18891
3   7      11     0.23404255      19.191489     1985-08-12 2015-10-01  30.13552
4  31      64     0.78048780      64.000000     1994-08-13 2015-10-01  21.13347
5  25      31     0.37804878      31.000000     1979-05-23 2015-10-01  36.35866
6   3      11     0.16176471      13.264706     1989-04-07 2015-10-01  26.48323
7   0       0     0.00000000       0.000000     <NA>       2015-10-01        NA
8  15      29     0.72500000      59.450000     1989-05-04 2015-10-01  26.40931
9   1       1     0.06666667       5.466667     1993-03-10 2015-10-01  22.55989
10 36      49     0.61250000      50.225000     1992-01-30 2015-10-01  23.66872
11  7      17     0.22972973      18.837838     1992-07-25 2015-10-01  23.18412
12  0       0     0.00000000       0.000000     1995-03-28 2015-10-01  20.51198
13  0       0     0.00000000       0.000000     1994-04-05 2015-10-01  21.48939
14  1       2     0.28571429      23.428571     1993-02-20 2015-10-01  22.60917
15  9      18     0.22500000      18.450000     1987-10-05 2015-10-01  27.98905
16  7       9     0.28125000      23.062500     1994-10-07 2015-10-01  20.98289
17  5       8     0.22222222      18.222222     1991-01-24 2015-10-01  24.68446
18  1       2     0.22222222      18.222222     1995-10-07 2015-10-01  19.98357
19  5       6     0.11320755       9.283019     1988-04-14 2015-10-01  27.46338
20  9      15     0.18750000      15.375000     1980-08-03 2015-10-01  35.15948

In [56]:
nrow(head(nhl_clean, 20))

[1] 20

In [57]:
nhl_clean |>
    filter(is.na(age))|>
    distinct(player_id, player_name)

   player_id player_name
1  8478393   Kyle Baun
2  8475247   Michael Latta
3  8469490   Tim Jackman
4  8470230   Daniel Paille
5  8471996   Bracken Kearns
6  8467514   Pavel Datsyuk
7  8476404   Andy Andreoff
8  8478584   Vojtech Mozik
9  8470852   Matt Moulson
10 8473565   Brian Strait
11 8471490   Adam Cracknell
12 8475161   Chris Brown
13 8471245   Dave Bolland
14 8475829   John Ramage
15 8477392   Hudson Fasching
16 8475759   Brandon Gormley
17 8473426   Mike Weber
18 8478371   Matt Lorito
19 8476619   Zack Mitchell
20 8477634   Trevor Murphy
21 8475328   Ben Sexton
22 8478911   Matt Roy
23 8479439   Jacob MacDonald
24 8481479   Brogan Rafferty
25 8481481   Blake Lizotte
26 8479330   Brandon Gignac
27 8479414   Nathan Bastian
28 8478975   Mason Marchment
29 8481515   Danil Yurtaykin
30 8479367   William Lockwood
⋮  ⋮         ⋮
38 8483641   Anton Levtchi
39 8483619   Filip Roos
40 8482176   Wyatt Kaiser
41 8480840   Oskar Bck
42 8482174   William Villeneuve
43 8483709   Abram Wiebe
44 8485388   Victor Eklund
45 8486166   Viking Gustafsson-Nyberg
46 8483760   Hunter McDonald
47 8482525   Ryan Tverberg
48 8483712   Ludvig Jansson
49 8482187   Ronan Seeley
50 8483444   Nathan Gaucher
51 8483687   Marek Alscher
52 8484793   Sacha Boisvert
53 8485406   Porter Martone
54 8483696   Cole O'Hara
55 8485467   Luke Haymes
56 8484169   Drew Fortescue
57 8484148   Oliver Bonk
58 8484220   David Reinbacher
59 8484380   Wilmer Skoog
60 8485395   James Hagens
61 8484999   Ilya Protas
62 8482873   Topias Vilen
63 8482731   Tyson Hinds
64 8484392   Felix Unger Sorum
65 8484794   Michael Brandsegg-Nygrd
66 8486169   Jake Livanavage
67 8484242   Brayden Yager

In [58]:
nhl_clean |>
    filter(is.na(age))|>
    select(
        player_id,
        player_name,
        season_start,
        team
        )

    player_id player_name             season_start team
1   8478393   Kyle Baun               2015         CHI
2   8475247   Michael Latta           2015         WSH
3   8469490   Tim Jackman             2015         ANA
4   8470230   Daniel Paille           2015         NYR
5   8471996   Bracken Kearns          2015         NYI
6   8467514   Pavel Datsyuk           2015         DET
7   8476404   Andy Andreoff           2015         L.A
8   8478584   Vojtech Mozik           2015         N.J
9   8470852   Matt Moulson            2015         BUF
10  8473565   Brian Strait            2015         NYI
11  8471490   Adam Cracknell          2015         EDM
12  8475161   Chris Brown             2015         WSH
13  8471245   Dave Bolland            2015         FLA
14  8475829   John Ramage             2015         CBJ
15  8477392   Hudson Fasching         2015         BUF
16  8475759   Brandon Gormley         2015         COL
17  8473426   Mike Weber              2015         WSH
18  8471996   Bracken Kearns          2016         NYI
19  8478371   Matt Lorito             2016         DET
20  8470852   Matt Moulson            2016         BUF
21  8471490   Adam Cracknell          2016         DAL
22  8476404   Andy Andreoff           2016         L.A
23  8477392   Hudson Fasching         2016         BUF
24  8473565   Brian Strait            2016         WPG
25  8476619   Zack Mitchell           2016         MIN
26  8477634   Trevor Murphy           2017         ARI
27  8477392   Hudson Fasching         2017         BUF
28  8476404   Andy Andreoff           2017         L.A
29  8476619   Zack Mitchell           2017         MIN
30  8470852   Matt Moulson            2017         BUF
⋮   ⋮         ⋮                       ⋮            ⋮
114 8483760   Hunter McDonald         2025         PHI
115 8482525   Ryan Tverberg           2025         TOR
116 8482408   Jeff Malott             2025         LAK
117 8483712   Ludvig Jansson          2025         FLA
118 8482187   Ronan Seeley            2025         CAR
119 8483444   Nathan Gaucher          2025         ANA
120 8483687   Marek Alscher           2025         FLA
121 8484793   Sacha Boisvert          2025         CHI
122 8485406   Porter Martone          2025         PHI
123 8483696   Cole O'Hara             2025         NSH
124 8485467   Luke Haymes             2025         TOR
125 8484169   Drew Fortescue          2025         NYR
126 8479414   Nathan Bastian          2025         DAL
127 8484148   Oliver Bonk             2025         PHI
128 8484220   David Reinbacher        2025         MTL
129 8480840   Oskar Bck               2025         DAL
130 8484380   Wilmer Skoog            2025         FLA
131 8482176   Wyatt Kaiser            2025         CHI
132 8481568   Alex Vlasic             2025         CHI
133 8485395   James Hagens            2025         BOS
134 8481481   Blake Lizotte           2025         PIT
135 8480874   Adam Ginning            2025         PHI
136 8484999   Ilya Protas             2025         WSH
137 8478911   Matt Roy                2025         WSH
138 8482873   Topias Vilen            2025         NJD
139 8482731   Tyson Hinds             2025         ANA
140 8484392   Felix Unger Sorum       2025         CAR
141 8484794   Michael Brandsegg-Nygrd 2025         DET
142 8486169   Jake Livanavage         2025         PIT
143 8484242   Brayden Yager           2025         WPG

In [59]:
mean(!is.na(nhl_clean$age))*100

[1] 98.58626

In [60]:
nhl_model_ready <- nhl_clean |>
    filter(!is.na(age))

#filtering out players whose age could not be matched with a player id on moneypuck

In [61]:
sum(is.na(nhl_model_ready$age))

[1] 0

In [62]:
summary(nhl_model_ready$age)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  18.05   23.42   26.14   26.67   29.51   45.63

In [63]:
nhl_model_ready |>
    arrange(age)|>
    select(player_name, season_start, age) |>
    slice_head(n = 10)

   player_name        season_start age
1  Alex Formenton     2017         18.05065
2  Filip Chytil       2017         18.07255
3  Matthew Schaefer   2025         18.07255
4  Jett Luchanko      2024         18.11362
5  Quinton Byfield    2020         18.11910
6  Clayton Keller     2016         18.17659
7  Connor Bedard      2023         18.20671
8  Jesperi Kotkaniemi 2018         18.23682
9  Mikhail Sergachev  2016         18.26968
10 Macklin Celebrini  2024         18.30253

In [66]:
nhl_outcomes <- nhl_model_ready |>
    arrange(player_id, season_start) |>
    group_by(player_id) |>
    mutate (
        next_season = lead(season_start),
        next_games_played = lead(games_played),
        next_points_per_82 = lead(points_per_82)
        ) |>
ungroup()

##starts with the whole dataset not just active cases

In [68]:
nhl_outcomes <- nhl_outcomes |>
    filter(next_season == season_start + 1) |>
##removes cases where players missed a season before returning

In [70]:
nhl_outcomes <- nhl_outcomes |>
    filter(
        games_played >= 30,
        next_games_played >= 30
        )

##minimum 30 games per season requirement in order for stats to be relevant

In [72]:
nhl_outcomes <- nhl_outcomes |>
    mutate(
        points_increase = 
        next_points_per_82 - points_per_82,

        percentage_increase = if_else(
            points_per_82 > 0,
            points_increase / points_per_82,
            NA_real_
            ),
        breakout = if_else (
            points_increase >= 15 &
            percentage_increase >= 0.25,
            1L,
            0L
            )
        ) |>
    filter(!is.na(breakout))

#define a breakout by putting it into a binary system
# 1  = breakout
# 0 = no breakout

In [73]:
nhl_outcomes |>
    count(breakout) |>
    mutate(percentage = n / sum(n) * 100)

  breakout n    percentage
1 0        4670 89.70419
2 1         536 10.29581

In [74]:
training_data <- nhl_outcomes |>
  filter(season_start <= 2022)

validation_data <- nhl_outcomes |>
  filter(season_start == 2023)

testing_data <- nhl_outcomes |>
  filter(season_start == 2024)

prediction_data <- nhl_model_ready |>
  filter(season_start == 2025)

In [75]:
range(training_data$season_start)
unique(validation_data$season_start)
unique(testing_data$season_start)
unique(prediction_data$season_start)

[1] 2015 2022

[1] 2023

[1] 2024

[1] 2025

In [76]:
tibble(
  dataset = c(
    "Training",
    "Validation",
    "Testing",
    "Prediction"
  ),
  rows = c(
    nrow(training_data),
    nrow(validation_data),
    nrow(testing_data),
    nrow(prediction_data)
  )
)

#looking to build a model with past information, validate on a later season
#test on a new season and generate real predictions for 2026/2027 season

  dataset    rows
1 Training   4112
2 Validation  552
3 Testing     542
4 Prediction  904

In [77]:
saveRDS(nhl_outcomes, 
        "Predict NHL Breakout 26-27/nhl_outcomes.rds"
        )