In [5]:
library(tidyverse)

getwd()
list.files()

[1] "C:/Users/rdela/nhl-breakout-project"

[1] "data.ipynb"                 "Predict NHL Breakout 26-27"

In [10]:
files <- list.files (
    path = "Predict NHL Breakout 26-27",
    full.names = TRUE
    )

files

 [1] "Predict NHL Breakout 26-27/NHL15-16.csv"
 [2] "Predict NHL Breakout 26-27/NHL16-17.csv"
 [3] "Predict NHL Breakout 26-27/NHL17-18.csv"
 [4] "Predict NHL Breakout 26-27/NHL18-19.csv"
 [5] "Predict NHL Breakout 26-27/NHL19-20.csv"
 [6] "Predict NHL Breakout 26-27/NHL20-21.csv"
 [7] "Predict NHL Breakout 26-27/NHL21-22.csv"
 [8] "Predict NHL Breakout 26-27/NHL22-23.csv"
 [9] "Predict NHL Breakout 26-27/NHL23-24.csv"
[10] "Predict NHL Breakout 26-27/NHL24-25.csv"
[11] "Predict NHL Breakout 26-27/NHL25-26.csv"

In [11]:
nhl_raw <- map_dfr (
    files,
    ~ read_csv (.x, show_col_types = FALSE)
    )
dim(nhl_raw)

[1] 50575   154

In [12]:
nhl_players <- nhl_raw |>
filter (situation == "all")

In [13]:
dim(nhl_players)

[1] 10115   154

In [15]:
nhl_players |>
count (season) |>
arrange (season)

   season n
1  2015    898
2  2016    887
3  2017    890
4  2018    906
5  2019    883
6  2020    913
7  2021   1003
8  2022    951
9  2023    924
10 2024    920
11 2025    940

In [16]:
nhl_players |>
select (
    name,
    season,
    team,
    position,
    games_played,
    I_F_goals,
    I_F_primaryAssists,
    I_F_secondaryAssists,
    I_F_points
    ) |>
head(20)

   name                season team position games_played I_F_goals
1  Mikko Koivu         2015   MIN  C        82           17
2  Trevor van Riemsdyk 2015   CHI  D        82            3
3  Kyle Quincey        2015   DET  D        47            4
4  Filip Forsberg      2015   NSH  L        82           33
5  Brian Campbell      2015   FLA  D        82            6
6  Chris Terry         2015   CAR  L        68            8
7  Kyle Baun           2015   CHI  R         2            0
8  James van Riemsdyk  2015   TOR  L        40           14
9  Scott Harrington    2015   TOR  D        15            0
10 Ryan Spooner        2015   BOS  C        80           13
11 Johan Larsson       2015   BUF  C        74           10
12 Josh Morrissey      2015   WPG  D         1            0
13 Christoph Bertschy  2015   MIN  C         3            0
14 Blake Pietila       2015   N.J  L         7            1
15 Michael Grabner     2015   TOR  R        80            9
16 Kerby Rychel        2015   CBJ  L        32            2
17 Zack Kassian        2015   EDM  R        36            3
18 Nikolay Goldobin    2015   S.J  R         9            1
19 Eric Gryba          2015   EDM  D        53            1
20 Dominic Moore       2015   NYR  C        80            6
   I_F_primaryAssists I_F_secondaryAssists I_F_points
1  18                 21                   56
2   7                  4                   14
3   0                  7                   11
4  14                 17                   64
5  12                 13                   31
6   2                  1                   11
7   0                  0                    0
8  10                  5                   29
9   0                  1                    1
10 29                  7                   49
11  5                  2                   17
12  0                  0                    0
13  0                  0                    0
14  1                  0                    2
15  5                  4                   18
16  6                  1                    9
17  2                  3                    8
18  1                  0                    2
19  2                  3                    6
20  5                  4                   15

In [17]:
saveRDS (
    nhl_players,
    "Predict NHL Breakout 26-27/nhl_players.rds"
    )